

# This file was *autogenerated* from the file khovanov_homology_conjecture_up_to_15_crossings.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_21 = Integer(21); _sage_const_20 = Integer(20); _sage_const_22 = Integer(22)

import regina
import ast


DTList = [
    "4 8 -12 2 -16 -6 -20 -18 -10 -14",
    "6 10 14 -18 2 -20 4 22 24 -8 -12 16",
    "8 -12 -16 -20 22 -2 24 -4 26 -6 28 10 14 18"
]

TorusList = [
    [
        [_sage_const_1 , _sage_const_7 , _sage_const_2 , _sage_const_6 ], [_sage_const_3 , _sage_const_9 , _sage_const_4 , _sage_const_8 ], [_sage_const_5 , _sage_const_1 , _sage_const_6 , _sage_const_10 ], [_sage_const_7 , _sage_const_3 , _sage_const_8 , _sage_const_2 ], [_sage_const_9 , _sage_const_5 , _sage_const_10 , _sage_const_4 ]
    ],
    [
        [_sage_const_1 , _sage_const_9 , _sage_const_2 , _sage_const_8 ], [_sage_const_3 , _sage_const_11 , _sage_const_4 , _sage_const_10 ], [_sage_const_5 , _sage_const_13 , _sage_const_6 , _sage_const_12 ], [_sage_const_7 , _sage_const_1 , _sage_const_8 , _sage_const_14 ],
        [_sage_const_9 , _sage_const_3 , _sage_const_10 , _sage_const_2 ], [_sage_const_11 , _sage_const_5 , _sage_const_12 , _sage_const_4 ], [_sage_const_13 , _sage_const_7 , _sage_const_14 , _sage_const_6 ]
    ],
    [
        [_sage_const_1 , _sage_const_13 , _sage_const_2 , _sage_const_12 ], [_sage_const_3 , _sage_const_15 , _sage_const_4 , _sage_const_14 ], [_sage_const_5 , _sage_const_17 , _sage_const_6 , _sage_const_16 ], [_sage_const_7 , _sage_const_19 , _sage_const_8 , _sage_const_18 ],
        [_sage_const_9 , _sage_const_21 , _sage_const_10 , _sage_const_20 ], [_sage_const_11 , _sage_const_1 , _sage_const_12 , _sage_const_22 ], [_sage_const_13 , _sage_const_3 , _sage_const_14 , _sage_const_2 ], [_sage_const_15 , _sage_const_5 , _sage_const_16 , _sage_const_4 ],
        [_sage_const_17 , _sage_const_7 , _sage_const_18 , _sage_const_6 ], [_sage_const_19 , _sage_const_9 , _sage_const_20 , _sage_const_8 ], [_sage_const_21 , _sage_const_11 , _sage_const_22 , _sage_const_10 ]
    ]
]

MirrorList = [
    [
        [_sage_const_1 , _sage_const_6 , _sage_const_2 , _sage_const_7 ], [_sage_const_3 , _sage_const_8 , _sage_const_4 , _sage_const_9 ], [_sage_const_5 , _sage_const_10 , _sage_const_6 , _sage_const_1 ], [_sage_const_7 , _sage_const_2 , _sage_const_8 , _sage_const_3 ], [_sage_const_9 , _sage_const_4 , _sage_const_10 , _sage_const_5 ]
    ],
    [
        [_sage_const_1 , _sage_const_8 , _sage_const_2 , _sage_const_9 ], [_sage_const_3 , _sage_const_10 , _sage_const_4 , _sage_const_11 ], [_sage_const_5 , _sage_const_12 , _sage_const_6 , _sage_const_13 ], [_sage_const_7 , _sage_const_14 , _sage_const_8 , _sage_const_1 ],
        [_sage_const_9 , _sage_const_2 , _sage_const_10 , _sage_const_3 ], [_sage_const_11 , _sage_const_4 , _sage_const_12 , _sage_const_5 ], [_sage_const_13 , _sage_const_6 , _sage_const_14 , _sage_const_7 ]
    ],
    [
        [_sage_const_1 , _sage_const_12 , _sage_const_2 , _sage_const_13 ], [_sage_const_3 , _sage_const_14 , _sage_const_4 , _sage_const_15 ], [_sage_const_5 , _sage_const_16 , _sage_const_6 , _sage_const_17 ], [_sage_const_7 , _sage_const_18 , _sage_const_8 , _sage_const_19 ],
        [_sage_const_9 , _sage_const_20 , _sage_const_10 , _sage_const_21 ], [_sage_const_11 , _sage_const_22 , _sage_const_12 , _sage_const_1 ], [_sage_const_13 , _sage_const_2 , _sage_const_14 , _sage_const_3 ], [_sage_const_15 , _sage_const_4 , _sage_const_16 , _sage_const_5 ],
        [_sage_const_17 , _sage_const_6 , _sage_const_18 , _sage_const_7 ], [_sage_const_19 , _sage_const_8 , _sage_const_20 , _sage_const_9 ], [_sage_const_21 , _sage_const_10 , _sage_const_22 , _sage_const_11 ]
    ]
]

for n in [_sage_const_1 ]:
    KnotRegina = regina.Link.fromDT(DTList[n])
    pd = list(ast.literal_eval(((KnotRegina.pd())[_sage_const_3 :-_sage_const_1 ]).replace("X", "")))

    Knot = Link(pd)
    Tor = Link(TorusList[n])
    Mir = Link(MirrorList[n])

    hom = Knot.khovanov_homology()
    torhom = Tor.khovanov_homology()
    mirhom = Mir.khovanov_homology()
    print(hom, "\n")
    print(torhom, "\n")
    print(mirhom, "\n")

    if hom == torhom:
        print("MATCH")
    elif hom == mirhom:
        print("MATCH")

